server:
  port: 9907
  error:
    include-message: always
  servlet:
    context-path: /zq_play
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hahaha?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&sessionVariables=sql_mode=''
    username: maiqi
    password: maiqi
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 500
      max-lifetime: 18000000
      minimum-idle: 30
      connection-timeout: 30000
      connection-test-query: SELECT 1
      pool-name: HiKariDataSource
      type: com.zaxxer.hikari.HikariDataSource
      idle-timeout: 180000
      auto-commit: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    admin:
      enabled: true


# OpenAPI
springdoc:
  writer-with-default-pretty-printer: true
  version: '@springdoc.version@'
  swagger-ui:
    use-root-path: true


#mybatis-blus 相关配置
mybatis-plus:
  #datasource
  mapper-locations: classpath:/mapper/*.xml
  #实体类扫描
  type-aliases-package: com.oceanum.labeling.entity
  #启动时是否检查 MyBatis XML 文件的存在，默认不检查
  check-config-location: true
  global-config:
    db-config:
      # 生成ID方式： AUTO 数据库自增  INPUT 自己输入  ASSIGN_UUID 默认生成器
      id-type: ASSIGN_UUID
      #逻辑删除字段
      #      logic-delete-field: deleted
      # 逻辑删除已删除值
      #      logic-delete-value: 1
      #逻辑删除未删除值
      #      logic-not-delete-value: 0
      #自身实现增加表前缀
      #table-prefix: dc_
      #是否显示LOGO
  configuration:
    ## 自动驼峰命名规则映射
    map-underscore-to-camel-case: true
    #打印sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# keycloak
keycloak:
  realm: extract
  auth-server-url: https://keycloak.oceanum.uat
  ssl-required: external
  resource: parsing-service
  disable-trust-manager: true
  credentials:
    secret: YizDHPo1FbVAGro4PJIp0p1Eeq2WXyCI
  use-resource-role-mappings: true
  bearerOnly: true
  principal-attribute: preferred_username
  policy-enforcer-config:
    enforcement-mode: PERMISSIVE
    lazy-load-paths: true
    paths:
      - name: swagger-ui
        path: '/swagger-ui/*'
        enforcementMode: DISABLED
        static: true
      - name: api-docs
        path: '/v3/api-docs/*'
        enforcementMode: DISABLED
        static: true
  security-constraints:
    - authRoles: '*'
      security-collections:
        - name: protected
          patterns: '/*'
    - security-collections:
        - name: swagger-ui
          patterns: '/swagger-ui/*'
        - name: api-docs
          patterns: '/v3/api-docs/*'
  enabled: true


logging:
  config: classpath:log4j2-labeling.xml


app:
  services:
    extracting:
      sync-url: http://10.50.17.104:7900/extracting/labels